name: toolife
description: Toolife app with Firebase
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_analytics: ^10.8.0

flutter:
  uses-material-design: true
